
version: "3.3"

services:
  pubsub:
    image: thekevjames/gcloud-pubsub-emulator:latest
    environment:
      - PUBSUB_PROJECT1=hem-integration-services,nft_details:nft_details_listener,classifier:class_listener,nft_marketplace_state:marketplace_listener,pub_nft_marketplace_state:pub_nft_marketplace_state_subscription
    ports:
      - "8681:8432"
    networks:
      armm-network:
        ipv4_address: 172.20.0.16
    security_opt:
      - no-new-privileges:true
    read_only: true

  database:
    image: postgres:14.5-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: armm
      POSTGRES_PASSWORD: armm
      POSTGRES_DB: armm
    volumes:
      - database_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    networks:
      armm-network:
        ipv4_address: 172.20.0.17
    security_opt:
      - no-new-privileges:true
    read_only: true


volumes:
  database_data:
    driver: local

networks:
  armm-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
