version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: armm
      POSTGRES_PASSWORD: armm
      POSTGRES_DB: armm
    volumes:
      - ./data:/var/lib/postgresql/data\
    security_opt:
      - no-new-privileges:true
    read_only: true
